Start the dev branch
MouadOutmane/inetum-realJobs pull request #12
Opened 2021-12-13 14:48 UTC by TomD011099

2021-12-13 15:16 UTC, DeKleineKobini requested changes
There appears to not be a consistent formatting either.

2021-12-13 15:16 UTC, DeKleineKobini commented on src/main/java/world/inetum/realdolmen/inetumrealJobs/controllers/VacancyController.java
>      ResponseEntity<List<Vacancy>> findAllVacanciesWithFilter(@RequestParam String functionTitle, @RequestParam String contractType, @RequestParam String country, @RequestParam String industry, @Reque
No access modifier?

2021-12-13 15:16 UTC, DeKleineKobini commented on src/main/java/world/inetum/realdolmen/inetumrealJobs/controllers/VacancyController.java
> +    Vacancy newVacancy(@Valid @RequestBody Vacancy newVacancy) {
No access modifier?

2021-12-13 15:16 UTC, DeKleineKobini commented on src/main/java/world/inetum/realdolmen/inetumrealJobs/controllers/VacancyController.java
> +    ResponseEntity<List<Vacancy>> findAllVacancies() {
No access modifier?

2021-12-13 15:16 UTC, DeKleineKobini commented on src/main/java/world/inetum/realdolmen/inetumrealJobs/controllers/VacancyController.java
> +    ResponseEntity<List<Vacancy>> findAllVacancies() {
You should use a DTO.

2021-12-13 15:16 UTC, DeKleineKobini commented on src/main/java/world/inetum/realdolmen/inetumrealJobs/controllers/VacancyController.java
> +    Vacancy newVacancy(@Valid @RequestBody Vacancy newVacancy) {
You should use a DTO (CreateDTO + ReadDTO as return type).

2021-12-13 15:16 UTC, DeKleineKobini commented on src/main/java/world/inetum/realdolmen/inetumrealJobs/controllers/VacancyController.java
>      ResponseEntity<List<Vacancy>> findAllVacanciesWithFilter(@RequestParam String functionTitle, @RequestParam String contractType, @RequestParam String country, @RequestParam String industry, @Reque
You should use a DTO.

2021-12-13 15:16 UTC, DeKleineKobini commented on src/main/java/world/inetum/realdolmen/inetumrealJobs/controllers/VacancyController.java
>      ResponseEntity<List<Vacancy>> findAllVacanciesWithFilter(@RequestParam String functionTitle, @RequestParam String contractType, @RequestParam String country, @RequestParam String industry, @Reque
Instead of this huge list of parameters, an object would be better.

2021-12-13 15:16 UTC, DeKleineKobini commented on src/main/java/world/inetum/realdolmen/inetumrealJobs/validators/VacancyValidator.java
> +@Component("beforeCreateVacancyValidator")
What does this name mean and where is it used?

2021-12-13 15:16 UTC, DeKleineKobini commented on src/test/java/world/inetum/realdolmen/inetumrealJobs/controllers/VacancyControllerTest.java
> +        MvcResult m = mockMvc.perform(get("/api/vacancies/?functionTitle=&contractType=&industry=&country=Chili&requiredYearsOfExperience=0"))
Result is never used?

2021-12-13 15:16 UTC, DeKleineKobini commented on src/test/java/world/inetum/realdolmen/inetumrealJobs/controllers/VacancyControllerTest.java
> +        MvcResult m = mockMvc.perform(get("/api/vacancies/?functionTitle=&contractType=&industry=&country=Belgium&requiredYearsOfExperience=3"))
Result is never used?

2021-12-13 15:16 UTC, DeKleineKobini commented on src/test/java/world/inetum/realdolmen/inetumrealJobs/controllers/VacancyControllerTest.java
> +public class VacancyControllerTest {
Should be called `VacancyControllerIT`, as it's an integration test.

2021-12-13 15:16 UTC, DeKleineKobini commented on src/test/java/world/inetum/realdolmen/inetumrealJobs/repositories/VacancySpecificationTest.java
>  public class VacancySpecificationTest {
Also seems more like integration tests to me?

2021-12-13 15:16 UTC, DeKleineKobini commented on src/main/java/world/inetum/realdolmen/inetumrealJobs/entities/Vacancy.java
>      private String contractType;
Seems like a limited value = enum?

2021-12-13 15:16 UTC, DeKleineKobini commented on src/main/java/world/inetum/realdolmen/inetumrealJobs/entities/Vacancy.java
>      private String postingDate;
Should be a `LocalDate` or `LocalDateTime` (if the time is important).

2021-12-13 15:16 UTC, DeKleineKobini commented on src/main/java/world/inetum/realdolmen/inetumrealJobs/entities/Vacancy.java
>      private Integer postalCode;
Should be a `String`?

2021-12-13 15:16 UTC, DeKleineKobini commented on src/test/java/world/inetum/realdolmen/inetumrealJobs/services/VacancyServiceTest.java
> +        assertEquals(addedVacancy.getCompanyName(), (foundEntity.orElse(null)).getCompanyName());
A null check should probably be done first?

2021-12-13 15:16 UTC, TomD011099 commented on src/main/java/world/inetum/realdolmen/inetumrealJobs/entities/Vacancy.java
> +    }
Use JSON-b

2021-12-13 15:16 UTC, TomD011099 commented on src/main/java/world/inetum/realdolmen/inetumrealJobs/validators/VacancyValidator.java
> +@Component("beforeCreateVacancyValidator")
Why is this named?

2021-12-13 15:16 UTC, TomD011099 commented on src/test/java/world/inetum/realdolmen/inetumrealJobs/controllers/VacancyControllerTest.java
> +                .andReturn();
Why return this?

2021-12-13 15:16 UTC, TomD011099 commented on src/test/java/world/inetum/realdolmen/inetumrealJobs/controllers/VacancyControllerTest.java
> +                .andReturn();
Why return this?

2021-12-13 15:16 UTC, TomD011099 commented on src/test/java/world/inetum/realdolmen/inetumrealJobs/controllers/VacancyControllerTest.java
> +        MvcResult m = mockMvc.perform(get("/api/vacancies/?functionTitle=&contractType=&industry=&country=Chili&requiredYearsOfExperience=0"))
Unused var

2021-12-13 15:16 UTC, TomD011099 commented on src/test/java/world/inetum/realdolmen/inetumrealJobs/controllers/VacancyControllerTest.java
> +        MvcResult m = mockMvc.perform(get("/api/vacancies/?functionTitle=&contractType=&industry=&country=Belgium&requiredYearsOfExperience=3"))
Unused var

2021-12-13 15:16 UTC, TomD011099 commented on src/test/java/world/inetum/realdolmen/inetumrealJobs/controllers/VacancyControllerTest.java
> +    public void findAllVacanciesWithFilter_GETBelgium3YearsOfExpVacancy_Success() throws Exception{
Shouldn't you check data data you get?

2021-12-13 15:16 UTC, TomD011099 commented on src/test/java/world/inetum/realdolmen/inetumrealJobs/services/VacancyServiceTest.java
> +        assertEquals(addedVacancy.getCompanyName(), (foundEntity.orElse(null)).getCompanyName());
Why still use the Optional, you know it's there

2021-12-14 09:45 UTC, merged

2021-12-14 09:45 UTC, DeKleineKobini commented
Merged due to upcoming issues otherwise, changed will be done in another branch.