Improve the integration test asserts
MouadOutmane/inetum-realJobs pull request #35
Opened 2021-12-22 10:15 UTC by DeKleineKobini

#20

2021-12-22 14:23 UTC, TomD011099 requested changes

2021-12-22 14:23 UTC, TomD011099 commented on inetum-realjobs-backend/src/test/java/world/inetum/realdolmen/realjobs/controllers/AuthenticationControllerIT.java
> +                .andExpect(jsonPath("$.roles[0]").value("ROLE_JOBSEEKER"));
Maybe use andExpectAll?

2021-12-22 14:23 UTC, TomD011099 commented on inetum-realjobs-backend/src/test/java/world/inetum/realdolmen/realjobs/controllers/VacancyControllerIT.java
> +                .andExpect(jsonPath("$").isEmpty());
Maybe use andExpectAll?

2021-12-22 14:23 UTC, TomD011099 commented on inetum-realjobs-backend/src/test/java/world/inetum/realdolmen/realjobs/controllers/VacancyControllerIT.java
> +                .andExpect(jsonPath("$.length()").value(3));
Maybe use andExpectAll?

2021-12-22 14:23 UTC, TomD011099 commented on inetum-realjobs-backend/src/test/java/world/inetum/realdolmen/realjobs/controllers/VacancyControllerIT.java
> +                .andExpect(jsonPath("$.functionTitle").value("Vendor"));
Maybe use andExpectAll?

2021-12-22 14:33 UTC, TomD011099 approved these changes

2021-12-23 10:32 UTC, redasaada approved these changes

2021-12-23 10:52 UTC, merged